name: verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

    - name: Install BATS
      run: |
        sudo add-apt-repository ppa:duggan/bats
        sudo apt-get update
        sudo apt-get install bats

    - uses: actions/checkout@v1

    - name: verify
      run: |
        make verify
